
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simple-server.fullname" . }}-secret
  labels:
    {{- include "simple-server.labels" . | nindent 4 }}
data:
  {{ $mongoDBURL := printf "%s%s%s%s%s%s%s" "mongodb://root:" .Values.mongodb.auth.rootPassword "@" .Release.Name "-" .Values.config.mongoService ":27017" | b64enc -}}
  MONGODB_URL: {{ $mongoDBURL }}
